# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_WHYRED_BOARD)	+= whyred_board.o
obj-$(CONFIG_WHYRED_DISPLAY)	+= display/
obj-$(CONFIG_WHYRED_TOUCH)	+= touch/
obj-$(CONFIG_WHYRED_AUDIO)	+= audio/
obj-$(CONFIG_WHYRED_CAMERA)	+= camera/
obj-$(CONFIG_WHYRED_POWER)	+= power/
obj-$(CONFIG_WHYRED_WLAN)	+= wlan/
